Fix copying wallet address from balances page
sushiswap/sushiswap-interface pull request #601
Opened 2022-02-08 15:49 UTC by zackharley

No longer copy shortened wallet address. Instead, copy the full address.

Fixes #595

2022-02-09 21:40 UTC, sambacha requested changes
if your removing `shortenAddress` why not also remove it here as well?

2022-02-09 21:44 UTC, zackharley commented
> if your removing `shortenAddress` why not also remove it here as well?

@sambacha If you're referring to Line 51, I figured there was a reason that it was put here in the first place (and that the `CopyHelper` was accidentally using the shortened address). Happy to remove it!

2022-02-11 17:55 UTC, zackharley commented
Done! @grod220

2022-02-11 18:51 UTC, grod220 approved these changes

2022-02-11 18:51 UTC, merged