Feat: Error reporting and Tracing
sushiswap/sushiswap-interface pull request #805
Opened 2022-05-23 19:48 UTC by sambacha

2022-05-26 03:54 UTC, sambacha commented
@matthewlilley

2022-06-02 11:33 UTC, matthewlilley requested changes
Looks like the multicall files included are uneeded now? Besides that this looks good.

2022-06-02 11:33 UTC, matthewlilley commented on next.config.js
> +  async headeres() {
Looks like a typo

2022-06-09 10:19 UTC, sambacha commented on next.config.js
> +  async headeres() {
https://github.com/sushiswap/sushiswap-interface/pull/821

2022-06-09 10:19 UTC, sambacha commented
closing in favour of https://github.com/sushiswap/sushiswap-interface/pull/821

2022-06-09 10:19 UTC, closed without merging